### ISSUE TITLE
Database migrations are now failing. I am using .NET Core 2.2.

### ISSUE THREAD

**Issue by markeaston63** [pekspro/EF-Migrations-Script-Generator-Task#11]
Says it cant find the command to run the migration.
I tried ticking the new .NET Core 3 checkbox - but failed also. That did not surprise me as I am using .NET Core 2.2.

**Comment by pekspro** [comment]
Hi
I it’s because your building machines are using .NET 3 where this tool is missing. As far as I know there is no nuget package for .NET 2.2 that solves this. Either way, I think you find the solution here:
https://github.com/pekspro/EF-Migrations-Script-Generator-Task/issues/9

But maybe I should improve the error message, it’s easy to get stuck on this.

**Comment by markeaston63** [comment]
Ahhh I see. Many thanks!

**Comment by pekspro** [comment]
I've improved both the documentation and logging messages so I'm closing this issue now.
