### ISSUE TITLE
Extension validation error - Must belong to same group

### ISSUE THREAD

**Issue by PierreLetter** [pekspro/EF-Migrations-Script-Generator-Task#25]
On azure DevOps Server 2020 RC2 I get the following issue when trying to install v0.0.51

Extension validation error
Task definition input 'installdependencies' and Task definition input 'nugetconfiguration' must belong to same group as they are dependent inputs for Task with ID 'acdefe1b-3f7e-474e-b545-5816baa90334'.

Indeed there is no "groupName" on any task, but not being familiar with VSTS addon creation I don't want to mess things more myself so just reporting it.

**Comment by pekspro** [comment]
Thank you for reporting this. I guess the problem is that the setting **Install dependencies for .NET Core 3** is in no group, and the setting **NuGet configuration file** is in the **Advanced group** and this is only shown when the first setting is checked.

I will fix this. Your timing is absolutely brilliant, since I had planned to work some stuff in the project tomorrow :-)

**Comment by pekspro** [comment]
@PierreLetter , now the tool has been updated to version 0.0.52 that should fix this issue. Could you do a test?

**Comment by PierreLetter** [comment]
Updates without error now. Thanks for the quick fix.
