### ISSUE TITLE
How to add a down script?

### ISSUE THREAD

**Issue by pts1989** [pekspro/EF-Migrations-Script-Generator-Task#35]
For my application I am looking to let the build server also generate the down migrations, but that SQL isn't generated. Is there a way to make that happen?

**Comment by pekspro** [comment]
This is not supported in this task :-/ It is kind of tricky since you need to know to which script you want to migrate.

All this said it is nothing that stops you from scripting this yourself :-) I think syntax of generating the down migration is:

    dotnet ef migrations script FromMigrationName ToMigrationName

And I think you could use this command to list all migrations:

    dotnet ef migrations list
